layout_spectrum: 0.5171858
name: Motni Bin Khalaf
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.4055649
  lightness: 0.4677276
  saturation: 0.8346034
  rhythmicContrast: 0.7630278
  brandColors:
    - '#FFFFFF'
    - '#E8E8E8'
    - '#D7D7D7'
    - '#F3F3F3'
    - '#B9B9B9'
typography_spectrum: 0.1498389
