typography_spectrum: 0.12455065152607858
color:
  saturation: 0.7408838402479887
  brandStrength: 0.6238633177708834
  lightness: 0.15056106424890459
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  rhythmicContrast: 0.02207562350668013
layout_spectrum: 0.4628492188639939
author:
  name: Motni
  email: m@6w.cc
  url: Motni.Net
name: Motni
navigation:
  - name: من نحن
    id: 9dd12faf-9b5e-4c39-a5c1-86dcacc46539
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Motni.Net
description: مطني
