typography_spectrum: 0.1498389
color:
  saturation: 0.8346034
  brandStrength: 0.3313641
  rhythmicContrast: 0.6503759
  brandColors:
    - '#FFFFFF'
    - '#876B3C'
    - '#8A8889'
    - '#595758'
    - '#D7C7B1'
  lightness: 0.7341568
layout_spectrum: 0.5171858
name: Motni Bin Khalaf
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
