color:
  saturation: 0.8346034
  brandStrength: 0.4106239
  rhythmicContrast: 0.7630278
  brandColors:
    - '#FFFFFF'
    - '#826635'
    - '#A98A57'
    - '#C0A16D'
    - '#878586'
  lightness: 0.4677276
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.5171858
typography_spectrum: 0.1498389
name: Motni Bin Khalaf
