typography_spectrum: 0.5820777639746666
color:
  saturation: 0.5390550929587334
  brandStrength: 0.8576215314678848
  lightness: 0.05305167124606669
  brandColors:
    - '#FFFFFF'
    - '#848283'
    - '#A4A2A3'
    - '#D1C094'
    - '#F1E3C7'
  rhythmicContrast: 0.036356592550873756
layout_spectrum: 0.03213525307364762
name: Motni
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Motni.Net
description: مطني
